# Generated by Django 2.2.12 on 2020-05-10 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSessions',
            new_name='Sessions',
        ),
        migrations.RenameModel(
            old_name='UserTimers',
            new_name='Timers',
        ),
    ]
