# Generated by Django 3.0.6 on 2020-05-11 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_auto_20200510_2124'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sessions',
            new_name='Session',
        ),
        migrations.RenameModel(
            old_name='Timers',
            new_name='Timer',
        ),
    ]
